blog1app/urls.py
from django.conf.urls import url 
from .views import *




urlpatterns = [


    url(r'^logout/$', Logout.as_view(),
        name='logout'),
    url(r'^login/$', Login.as_view(),
        name='login'),



	url(r'^$', HomeView.as_view(), name='home'),
	url(r'^register/$', RegView.as_view(), name='reg'),
	url(r'^thanku/$', ThankuView.as_view(), name='thanku'),
	url(r'^blogcreate/$', BlogCreateView.as_view(), name='blogcreate'),
	url(r'^videocreate/$', VideoCreateView.as_view(), name='videocreate'),


 ]

blog1project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog1app.urls', namespace='blog1app'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog1app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User



# class TimeStamp(models.Model):
#     created_at = models.DateTimeField(auto_now_add=True, null=True)
#     updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
#     deleted_at = models.DateTimeField(null=True, blank=True)

#     class Meta:
#         abstract = True

#     def delete(self):
#         self.deleted_at = timezone.now()
#         super().save()

class Blog(models.Model):
    title = models.CharField(max_length=500)
    image = models.ImageField(upload_to='blog/')
    content = models.TextField()
    author = models.ForeignKey(User)

    def __str__(self):
        return self.title



class Video(models.Model):
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=255)


    def __str__(self):
        return self.title

blog1app/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User



class DateTimeInput(forms.DateInput):
    input_type = 'time'


class UserForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': 'true',
                    'placeholder': 'Password...',
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': 'true',
                    'placeholder': 'Confirm password...',
    }))

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "password1",
            "password2",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        self.fields["username"].widget.attrs.update(
            {'placeholder': 'Username', 'required': 'true'})
        self.fields["email"].widget.attrs.update(
            {'placeholder': 'E-Mail', 'required': 'true'})

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if not password2:
            raise forms.ValidationError("You must confirm your password")
        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match")
        return password2







class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control'}))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}))



class BlogForm(forms.ModelForm):
	class Meta:
		model = Blog
		fields = '__all__'



class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ['url', 'title']
        # widgets = {
        #     'title': forms.TextInput(attrs={
        #         'class': 'form-control',
        #         'placeholder': 'Title',
        #         'required': 'True'}),
        #     'url': forms.TextInput(attrs={
        #         'class': 'form-control',
        #     }),
        # }

blog1app/views.py
from django.views.generic import *
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse_lazy
from .forms import *
from urllib.parse import urlparse, parse_qs





class Logout(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class Login(FormView):
    template_name = "adminlogin.html"
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_superuser:
            login(self.request, user)
        else:
            return render(self.request, self.template_name, {
                'form': form,
                'errors': 'Incorrect username or password'})
        return super().form_valid(form)


class HomeView(ListView):
	template_name='clienthome.html'
	model = Blog
	
	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, *kwargs)
		context['blogs'] = Blog.objects.filter(author=self.request.user)
		context['videos'] = Video.objects.all()
		return context




class RegView(CreateView):
    template_name = 'regform.html'
    form_class = UserForm
    success_url = '/'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password2']
        user = form.save()
        user.set_password(password)
        user.save()

        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super().form_valid(form)


class ThankuView(TemplateView):
	template_name = 'thanku.html'

class BlogCreateView(CreateView):
	template_name = 'blogcreate.html'
	form_class = BlogForm
	success_url = '/thanku/'



class VideoCreateView(CreateView):
    template_name = 'videocreate.html'
    model = Video
    form_class = VideoForm
    success_url = '/'

    def form_valid(self, form):
        url = form.cleaned_data['url']
        url_data = urlparse(url)
        query = parse_qs(url_data.query)
        video = query['v'][0]
        form.instance.url = video
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_name'] = 'videos'
        return context

 

templates/adminlogin.html
<!DOCTYPE html>
<html>
<head>
	<title>login form</title>
</head>
<body>

	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<button>Submit</button>
	</form>
</body>
</html>

templates/blogcreate.html
<!DOCTYPE html>
<html>
<head>
	<title>blog form</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}
	<button>submit</button>
</form>
</body>
</html>

templates/clienthome.html
<!DOCTYPE html>
<html>
<head>
	<title>my site</title>
</head>
<body>
<h3>hello everyone.</h3>
<h2>
	{% if request.user.is_authenticated %}

	Logged in User: {{request.user.username}}<br>

	<a href="{% url 'blog1app:logout' %}">Logout</a><br>

	<h3>Blogs by {{request.user.username}}</h3>
	{% for blog in blogs %}
	<li>{{blog.title}}</li>
	{% endfor %}
	{% else %}
	<a href="{% url 'blog1app:login' %}">Login</a>
	{% endif %}


{% for video in videos %}

<h3>{{video.title}}</h3>
<iframe width="360" height="240" src="https://www.youtube.com/embed/{{video.url}}?ecver=1" frameborder="0" allowfullscreen></iframe>

{% endfor %}

</h2>
</body>
</html>

templates/regform.html
<!DOCTYPE html>
<html>
<head>
	<title>registrstion</title>
</head>
<body>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button>Register</button>
</form>
</body>
</html>

templates/thanku.html
<!DOCTYPE html>
<html>
<head>
	<title>thanku</title>
</head>
<body>
<h3>thanku for your form submission</h3>
<a href="/">return to home</a>
</body>
</html>

templates/videocreate.html
<!DOCTYPE html>
<html>
<head>
	<title>\video \create</title>
</head>
<body>
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" name="Submit">
	</form>
</body>
</html>